# Generated by Django 4.1 on 2022-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.IntegerField(verbose_name='Cep')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('reference', models.CharField(max_length=100, verbose_name='Referência')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('publicPlace', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('state', models.CharField(max_length=30, verbose_name='Estado')),
            ],
        ),
    ]
