# Generated by Django 4.0.6 on 2022-08-29 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100, verbose_name='Portador')),
                ('number', models.IntegerField(verbose_name='Número do cartão')),
                ('valid_until', models.DateField(verbose_name='Válido até')),
                ('cvv', models.IntegerField(verbose_name='Código de verificação')),
            ],
            options={
                'db_table': 'credit_card',
            },
        ),
    ]
