# Generated by Django 4.0.5 on 2022-08-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cidade'),
        ),
    ]
