# Generated by Django 4.0.5 on 2022-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_address_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.CharField(max_length=60, verbose_name='Cidade'),
        ),
    ]
