# Generated by Django 4.1 on 2022-08-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_productimage_delete_state_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(default=0, verbose_name='Total Sales'),
        ),
    ]
